# Please refer to the btrbk.conf(5) man-page for a complete
# description of all configuration options.
#
# Note that the options can be overridden per volume/subvolume/target
# in the corresponding sections.

# Enable transaction log
transaction_log            /var/log/btrbk.log

# Specify SSH private key for remote connections
ssh_identity               /etc/btrbk/ssh/id_ed25519
ssh_user                   root

# Enable stream buffer. Adding a buffer between the sending and
# receiving side is generally a good idea.
# NOTE: If enabled, make sure to install the "mbuffer" package!
stream_buffer              256m

# Always create snapshots. Set this to "ondemand" to only create
# snapshots if the target volume is reachable. Set this to "no" if
# snapshot creation is done by another instance of btrbk.
snapshot_create            always

# Perform incremental backups (set to "strict" if you want to prevent
# creation of non-incremental backups if no parent is found).
incremental                yes

# Specify after what time (in full hours after midnight) backups/
# snapshots are considered as a daily backup/snapshot
preserve_hour_of_day       3

# Specify on which day of week weekly/monthly backups are to be
# preserved.
preserve_day_of_week       sunday

# Preserve all snapshots for a minimum period of time.
snapshot_preserve_min      1d

# Retention policy for the source snapshots.
snapshot_preserve          48h 9d 6w

# Preserve all backup targets for a minimum period of time.
target_preserve_min        no

# Retention policy for backup targets:
target_preserve            72h 14d 8w 6m 3y

# Enable lock file support: Ensures that only one instance of btrbk
# can be run at a time.
lockfile                   /var/lock/btrbk.lock

volume /mnt/btr_pool
  snapshot_dir .snapshots
  snapshot_create always
  target          ssh://nas.tail54020.ts.net/volume1/Backup/raidho
  ssh_user        jcorbin
  ssh_identity    /etc/btrbk/ssh/id_ed25519
  backend_remote  btrfs-progs-sudo
  subvolume home/jcorbin
