syntax on

" Have Vim load indentation rules according to the detected filetype.
if has("autocmd")
  filetype indent on
endif

set showcmd    " Show (partial) command in status line.
set showmatch  " Show matching brackets.
set ignorecase " Do case insensitive matching
set smartcase  " Do smart case matching
set incsearch  " Incremental search
"set autowrite " Automatically save before commands like :next and :make
"set hidden    " Hide buffers when they are abandoned
"set mouse=a   " Enable mouse usage (all modes) in terminals
set nobackup   " Don't keep a backup file
set nohls      " no highlight while searching
set ruler

" Paste Toggling with <F11>
map <F11> setenvpastemap
set pastetoggle=<F11>

" Bind , to repeat last macro
map , @@

" Show tabs, trailing spaces, and line wraps
set list listchars=tab:^-,trail:_,extends:+,nbsp:.
set background=dark

if has("gui_running")
	set guifont=DejaVu\ Sans\ Mono\ 6,Bitstream\ Vera\ Sans\ Mono\ 6
	" guioptions:
	"   a - autoselect
	"   c - console dialogs
	"   e - gui tabline
	"   i - icon hint
	"   m - menubar
	"   g - grey out menu items
	"   r - right scroll always
	set guioptions=aceimgr
	set guiheadroom=0
	colorscheme moria
else
	colorscheme desert
endif

let perl_include_pod = 1
let perl_want_scope_in_variables = 1
let perl_extended_vars = 1
let perl_fold = 0
let javaScript_fold = 1
let xml_use_xhtml = 1
let xml_no_auto_nesting = 1
let php_folding = 0

" augroup cleanup
" au BufWritePre * :normal mz:%s/ *$//:normal 'z
" augroup END

map ; ::

set virtualedit=all

set noexpandtab
set tabstop=2
set shiftwidth=2

set foldmethod=indent
set swapsync=
set modeline
set nu
set laststatus=2

" C-t for new tab
map <C-T> <Esc>:tabnew<CR>
