set background=dark

if has("gui_running")
	set guifont=Bitstream\ Vera\ Sans\ Mono\ 9
	set guioptions=acgit
	colorscheme moria
else
	colorscheme desert
endif

let perl_include_pod = 1
let perl_want_scope_in_variables = 1
let perl_extended_vars = 1
let perl_fold = 1
let javaScript_fold = 1
let xml_use_xhtml = 1
let xml_no_auto_nesting = 1

" augroup cleanup
" au BufWritePre * :normal mz:%s/ *$//:normal 'z
" augroup END

map ; ::

set virtualedit=all

set noexpandtab
set tabstop=4
set shiftwidth=4

set foldmethod=indent
set swapsync=
