#!/bin/sh
set -e
set -x

if [ "$1" = "inner" ]; then
    # Launch dbus if not started
    if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
       eval $(dbus-launch --sh-syntax --exit-with-session)
    fi

    [[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
    setxkbmap dvorak -option ctrl:nocaps

    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1&

    #/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh&
    /usr/bin/gnome-keyring-daemon --start --components=secrets,ssh&

    nm-applet&

    xterm&

    exec awesome
fi

exec ck-launch-session ssh-agent $0 inner "$@"
