if which fortune >/dev/null 2>&1 && [ ! -f ~/.no_fortune_motd ]; then
	echo
	fortune -a | sed -e 's/^/    /'
	echo
fi

autoload -U compinit
compinit

export EDITOR=vim
if which most>/dev/null; then
	export PAGER=$(which most)
elif which less>/dev/null; then
	export LESS='-MRci'
	export PAGER=$(which less)
fi

alias l=ls
