syntax on

" Have Vim load indentation rules according to the detected filetype.
if has("autocmd")
  filetype indent on
endif

set showcmd    " Show (partial) command in status line.
set showmatch  " Show matching brackets.
set ignorecase " Do case insensitive matching
set smartcase  " Do smart case matching
set incsearch  " Incremental search
"set autowrite " Automatically save before commands like :next and :make
"set hidden    " Hide buffers when they are abandoned
"set mouse=a   " Enable mouse usage (all modes) in terminals
set nobackup   " Don't keep a backup file
set nohls      " no highlight while searching
set ruler

" Paste Toggling with <F11>
map <F11> setenvpastemap
set pastetoggle=<F11>

" Bind , to repeat last macro
map , @@

" Show tabs, trailing spaces, and line wraps
set list listchars=tab:^-,trail:_,extends:+
