#!/bin/bash
# before: path
# after: arrayutil

# TODO: noop when not on OS-X and/or no brew installed gnu

# gnu toolchain from homebrew

gnu_brews=(coreutils gnu-sed)

no_gnu()
{
    local IFS=:
    for gnu_brew in "${gnu_brews[@]}"; do
        brew_dir=/usr/local/opt/$gnu_brew
        # shellcheck disable=SC2086
        PATH=$(without $brew_dir/libexec/gnubin $PATH)
        # shellcheck disable=SC2086
        MANPATH=$(without $brew_dir/libexec/gnuman $MANPATH)
    done
    export PATH MANPATH
    alias ls='ls -Fhb'
}

re_gnu()
{
    local IFS=:
    for gnu_brew in "${gnu_brews[@]}"; do
        brew_dir=/usr/local/opt/$gnu_brew
        if [ -d "$brew_dir" ]; then
            # shellcheck disable=SC2086
            PATH=$(prepend $brew_dir/libexec/gnubin $PATH)
            # shellcheck disable=SC2086
            MANPATH=$(prepend $brew_dir/libexec/gnuman $MANPATH)
        fi
    done
    export PATH MANPATH
    alias ls='ls -Fhb --time-style=long-iso --color=auto'
}

if [ -n "$USE_GNU" ]; then
	re_gnu
else
	no_gnu
fi
