#!/bin/bash
# before: path
# after: arrayutil

# TODO: noop when not on OS-X and/or no brew installed gnu

# gnu toolchain from homebrew

gnu_brews=(coreutils gnu-sed)

no_gnu()
{
    USE_GNU=
    local IFS=:
    for gnu_brew in "${gnu_brews[@]}"; do
        brew_dir=/usr/local/opt/$gnu_brew
        # shellcheck disable=SC2086
        PATH=$(without $brew_dir/libexec/gnubin $PATH)
        # shellcheck disable=SC2086
        MANPATH=$(without $brew_dir/libexec/gnuman $MANPATH)
    done
    export PATH MANPATH USE_GNU
    # shellcheck source=/dev/null
    source ~/.aliases
}

re_gnu()
{
    USE_GNU=1
    local IFS=:
    for gnu_brew in "${gnu_brews[@]}"; do
        brew_dir=/usr/local/opt/$gnu_brew
        if [ -d "$brew_dir" ]; then
            # shellcheck disable=SC2086
            PATH=$(prepend $brew_dir/libexec/gnubin $PATH)
            [ -z "$MANPATH" ] && MANPATH="$(man -w)"
            # shellcheck disable=SC2086
            MANPATH=$(prepend $brew_dir/libexec/gnuman $MANPATH)
        fi
    done
    export PATH MANPATH USE_GNU
    # shellcheck source=/dev/null
    source ~/.aliases
}

re_gnu
