#!/bin/sh
# after: arrayutil

# shellcheck source=/dev/null
[ -s "$HOME/.gvm/scripts/gvm" ] && . "$HOME/.gvm/scripts/gvm"

altgoroot()
{
    if [ -n "$GOROOT" ]; then
        PATH=$(IFS=:; without "$GOROOT/bin" $PATH)
    fi
    GOROOT=$1
    PATH=$(IFS=:; prepend "$GOROOT/bin" $PATH)
    export GOROOT PATH
}

altgopath()
{
    if [ -n "$GOPATH" ]; then
        PATH=$(IFS=:; without "$GOPATH/bin" $PATH)
    fi
    GOPATH=$1
    PATH=$(IFS=:; prepend "$GOPATH/bin" $PATH)
    export GOPATH PATH
}

goclone()
{
    name="$1"
    dest="$GOPATH/src/$name"
    [ -d "$dest" ] || mkdir -p "$dest"
    case "$name" in
    gh/*)
        goclone "github.com/${name#*/}"
        ;;
    github.com/*)
        git clone "gh:${name#*/}" "$dest"
        ;;

    *)
        echo "Not sure how to goclone $name" >&2
        return 1
        ;;
    esac
}

# vim:set ft=zsh:
