#!/bin/zsh
# after: completion
# after: compose
# after: editor
# after: history
# after: vi-mode-cursor

if [ -f ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

    ZSH_HIGHLIGHT_STYLES[default]=none
    ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=131,bold
    ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=034
    ZSH_HIGHLIGHT_STYLES[alias]=fg=178
    ZSH_HIGHLIGHT_STYLES[builtin]=fg=178
    ZSH_HIGHLIGHT_STYLES[function]=fg=178
    ZSH_HIGHLIGHT_STYLES[command]=fg=178
    ZSH_HIGHLIGHT_STYLES[precommand]=fg=103
    ZSH_HIGHLIGHT_STYLES[commandseparator]=fg=034
    ZSH_HIGHLIGHT_STYLES[hashed-command]=fg=178
    ZSH_HIGHLIGHT_STYLES[path]=fg=065
    ZSH_HIGHLIGHT_STYLES[globbing]=fg=067
    ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=075
    ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=fg=067
    ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=fg=067
    ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=fg=178
    ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=065
    ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=065
    ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=067
    ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=044
    ZSH_HIGHLIGHT_STYLES[assign]=fg=178

fi
