#!/bin/sh

add_path_component()
{
    [ -d $1 ] || return
    echo $PATH | grep -Fq "$1" && return
    export PATH=$PATH:$1
}

for dir in $HOME/bin \
           /var/lib/gems/*/bin \
           /opt/mit-scheme/bin
add_path_component $dir
