#!/bin/sh

without_colon_component()
{
    eval "echo \$$1" | tr ':' '\n' | grep -Fxv "$2" | tr '\n' ':'
}

remove_colon_component()
{
    export $1=$(without_colon_component "$1" "$2")
}

append_colon_component()
{
    [ -d $2 ] && export $1=$(without_colon_component "$1" "$2"):$2
}

prepend_colon_component()
{
    [ -d $2 ] && export $1=$2:$(without_colon_component "$1" "$2")
}

append_colon_component PATH /sbin
append_colon_component PATH /usr/sbin
append_colon_component PATH /usr/local/sbin

prepend_colon_component PATH $HOME/.local/bin
prepend_colon_component PATH $HOME/bin

prepend_colon_component PATH /usr/local/bin
prepend_colon_component PATH /usr/local/git/bin

# gnu toolchain from homebrew
prepend_colon_component PATH    /usr/local/opt/coreutils/libexec/gnubin
prepend_colon_component MANPATH /usr/local/opt/coreutils/libexec/gnuman

export PATH=$(echo $PATH | tr -s :)

no_gnu()
{
    remove_colon_component PATH    /usr/local/opt/coreutils/libexec/gnubin
    remove_colon_component MANPATH /usr/local/opt/coreutils/libexec/gnuman
    alias ls='ls -Fhb'
}

re_gnu()
{
    prepend_colon_component PATH    /usr/local/opt/coreutils/libexec/gnubin
    prepend_colon_component MANPATH /usr/local/opt/coreutils/libexec/gnuman
    alias ls='ls -Fhb --time-style=long-iso --color=auto'
}

export PATH=./node_modules/.bin:$PATH
