#!/bin/sh

append_path_component()
{
    [ -d $1 ] || return
    echo $PATH | grep -Fq "$1" && return
    export PATH=$PATH:$1
}

prepend_path_component()
{
    [ -d $1 ] || return
    echo $PATH | grep -Fq "$1" && return
    export PATH=$1:$PATH
}

# append_path_component /sbin
# append_path_component /usr/sbin
# append_path_component $HOME/bin
# append_path_component $HOME/.local/bin
# if [ -d /var/lib/gems ]; then
#     append_path_component /var/lib/gems/*/bin
# fi
# append_path_component /opt/mit-scheme/bin

cuda_root=/Developer/NVIDIA/CUDA-5.0
export DYLD_LIBRARY_PATH=$cuda_root/lib

export PATH=/opt/local/libexec/gnubin:/opt/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Users/jcorbin/bin:$cuda_root/bin
