#!/bin/sh

add_path_component()
{
    [ -d $1 ] || return
    echo $PATH | grep -Fq "$1" && return
    export PATH=$PATH:$1
}

if [ -d /opt/local/libexec/gnubin ]; then
    export PATH=/opt/local/libexec/gnubin:$(
        echo $PATH | tr : '\n' | grep -Fvx /opt/local/libexec/gnubin | tr '\n' :
    )
fi

add_path_component /sbin
add_path_component /usr/sbin
add_path_component /opt/local/bin
add_path_component $HOME/bin
add_path_component $HOME/.local/bin
if [ -d /var/lib/gems ]; then
    add_path_component /var/lib/gems/*/bin
fi
add_path_component /opt/mit-scheme/bin
