#!/bin/sh

# Dir Colors
if which dircolors >/dev/null 2>&1; then
    if [ -n "$TERM" ] && [ $(tput colors) -eq 256 ]; then
        eval $(dircolors ~/.dircolors/solarized/dircolors.256dark)
    else
        eval $(dircolors ~/.dircolors/solarized/dircolors.ansi-universal)
    fi
fi
