#!/bin/sh

# Try to fix broken $TERM
if [ -n "$TERM" ]; then if which tput &>/dev/null; then while true; do
    tput longname &>/dev/null && break
    [ -t 2 ] && echo -n "TERM=$TERM didn't work out..." >&2

    # if we ship a source for $TERM, and it's compiled yet, compile it and try again
    if [ -f $HOME/.terminfo.src/$TERM.terminfo ] && ! [ -f $HOME/.terminfo/${TERM:0:1}/$TERM ]; then
        tic $HOME/.terminfo.src/$TERM.terminfo
        if tput longname &>/dev/null; then
            [ -t 2 ] && echo "compiled ~/.terminfo worked!" >&2
            break
        fi
    fi

    # if -256color, try lower coler version
    if [[ $TERM = *-256color ]] && tput -T${TERM%-256color} longname &>/dev/null; then
        export TERM=${TERM%-256color}
        [ -t 2 ] && echo "using TERM=$TERM instead." >&2
        break
    fi

    # hmm, well if it's not linux, try that
    if [ $TERM != linux ] && tput -Tlinux longname &>/dev/null; then
        export TERM=linux
        [ -t 2 ] && echo "using TERM=$TERM instead." >&2
        break
    fi

    # finally, fallback on vt100
    export TERM=vt100
    [ -t 2 ] && echo "falling back to TERM=$TERM instead." >&2
done; fi; fi
