#!/bin/bash

export PIP_DOWNLOAD_CACHE=~/.pip/download_cache

VIRTUALENVWRAPPER_PYTHON=$(which python3)

if virtualenvwrapper=$(which virtualenvwrapper.sh 2>/dev/null); then
    source $virtualenvwrapper
    export WORKON_HOME=~/.virtualenv
fi
