#!/bin/sh
# before: path
# after: colon_component
# after: usr_local_path

# TODO: noop when not on OS-X and/or no brew installed gnu

# gnu toolchain from homebrew

no_gnu()
{
    remove_colon_component PATH    /usr/local/opt/coreutils/libexec/gnubin
    remove_colon_component MANPATH /usr/local/opt/coreutils/libexec/gnuman
    remove_colon_component PATH    /usr/local/opt/gnu-sed/libexec/gnubin
    remove_colon_component MANPATH /usr/local/opt/gnu-sed/libexec/gnuman
    alias ls='ls -Fhb'
}

re_gnu()
{
    prepend_colon_component PATH    /usr/local/opt/coreutils/libexec/gnubin
    prepend_colon_component MANPATH /usr/local/opt/coreutils/libexec/gnuman
    prepend_colon_component PATH    /usr/local/opt/gnu-sed/libexec/gnubin
    prepend_colon_component MANPATH /usr/local/opt/gnu-sed/libexec/gnuman
    alias ls='ls -Fhb --time-style=long-iso --color=auto'
}

re_gnu
