#!/bin/sh
# before: path
# after: arrayutil
# after: usr_local_path

# TODO: noop when not on OS-X and/or no brew installed gnu

# gnu toolchain from homebrew

no_gnu()
{
    local IFS=:
    PATH=$(without /usr/local/opt/coreutils/libexec/gnubin $PATH)
    PATH=$(without /usr/local/opt/gnu-sed/libexec/gnubin $PATH)
    MANPATH=$(without /usr/local/opt/coreutils/libexec/gnuman $MANPATH)
    MANPATH=$(without /usr/local/opt/gnu-sed/libexec/gnuman $MANPATH)
    export PATH MANPATH
    alias ls='ls -Fhb'
}

re_gnu()
{
    local IFS=:
    PATH=$(prepend /usr/local/opt/coreutils/libexec/gnubin $PATH)
    PATH=$(prepend /usr/local/opt/gnu-sed/libexec/gnubin $PATH)
    MANPATH=$(prepend /usr/local/opt/coreutils/libexec/gnuman $MANPATH)
    MANPATH=$(prepend /usr/local/opt/gnu-sed/libexec/gnuman $MANPATH)
    export PATH MANPATH
    alias ls='ls -Fhb --time-style=long-iso --color=auto'
}

if [ -n "$USE_GNU" ]; then
	re_gnu
else
	no_gnu
fi
