#!/bin/sh
# before: path
# after: arrayutil

cuda_root=/Developer/NVIDIA/CUDA-5.0
if [ -d "$cuda_root" ]; then
    export PATH=$(IFS=:; append $cuda_root/bin $PATH)
    export DYLD_LIBRARY_PATH=$(IFS=:; append $cuda_root/lib $DYLD_LIBRARY_PATH)
fi
