#!/bin/bash
# after: term

if [ -d ~/.dircolors ] && type dircolors &>/dev/null; then
    if [ "$COLORTERM" = "truecolor" ]; then
        eval "$(dircolors ~/.dircolors/darkula-truecolor)"
    elif [ "$(tput colors)" -eq 256 ]; then
        eval "$(dircolors ~/.dircolors/darkula-256)"
    else
        eval "$(dircolors ~/.dircolors/ansi-universal)"
    fi
fi

# Better than nothing for BSD ls
# from https://github.com/seebi/dircolors-solarized/issues/10
export CLICOLOR=1
export LSCOLORS="gxfxbEaEBxxEhEhBaDaCaD"
