#!/bin/bash
# after: term

# Want NeoVim
EDITOR=$(command -v nvim 2>/dev/null)

# Fallback to Vim
[ -x "$EDITOR" ] || EDITOR=$(command -v vim 2>/dev/null)

# Settle for Vi
[ -x "$EDITOR" ] || EDITOR=$(command -v vi 2>/dev/null)

export EDITOR
