#!/bin/sh
# after: arrayutil

[ -d "$HOME/go/bin" ] && export PATH=$(IFS=:; prepend "$HOME/go/bin" $PATH)

goclone()
{
    name="$1"
    dest="$(go env GOPATH)/src/$name"
    [ -d "$dest" ] || mkdir -p "$dest"
    case "$name" in
    gh/*)
        goclone "github.com/${name#*/}"
        ;;
    github.com/*)
        git clone "gh:${name#*/}" "$dest"
        ;;

    *)
        echo "Not sure how to goclone $name" >&2
        return 1
        ;;
    esac
}
