#!/bin/bash
# before: path
# after: arrayutil
# after: usr_local_path
# after: sbin_path

# add_home_paths adds ~/bin and ~/.local/bin to $PATH if they exist.
add_home_paths()
{
    local IFS=:

    # shellcheck disable=2086
    [ -d "$HOME/.local/bin" ] && PATH=$(prepend "$HOME/.local/bin" $PATH)

    # shellcheck disable=2086
    [ -d "$HOME/bin" ] && PATH=$(prepend "$HOME/bin" $PATH)

    for python_lib in "$HOME"/Library/Python/3*; do
        if [ -d "$python_lib/bin" ]; then
            # shellcheck disable=2086
            PATH=$(prepend "$python_lib/bin" $PATH)
            break
        fi
    done

    export PATH
}

add_home_paths
