#!/bin/sh
# before: path
# after: colon_component
# after: sbin_path

prepend_colon_component PATH $HOME/.local/bin
prepend_colon_component PATH $HOME/bin

for python_lib in $HOME/Library/Python/*; do
    if [ -d "$python_lib" ]; then
        force_prepend_colon_component PATH $python_lib/bin
        break
    fi
done
