#!/bin/sh
# before: nodejs
# after: bootstrap
# after: arrayutil

if [ -e "$HOME/.nvm/nvm.sh" ]; then
    if [ -f "$HOME/.nvm/alias/default" ]; then
        nvm_default=$(cat "$HOME/.nvm/alias/default")
        export PATH=$(IFS=:; prepend  "$HOME/.nvm/v${nvm_default}/bin" $PATH)
    fi

    nvm()
    {
        source "$HOME/.nvm/nvm.sh"
        nvm "$@"
    }
fi
