#!/bin/sh
# before: nodejs
# after: bootstrap

if [ -e "$HOME/.nvm/nvm.sh" ]; then
    if [ -f "$HOME/.nvm/alias/default" ]; then
        prepend_colon_component PATH "$HOME/.nvm/v$(cat "$HOME/.nvm/alias/default")/bin"
    fi

    nvm()
    {
        source "$HOME/.nvm/nvm.sh"
        nvm "$@"
    }
fi
