#!/bin/bash
# after: term

if which less>/dev/null; then
    PAGER="$(which less)"
    export PAGER

    # sets default options to less
    export LESS='-SMRci'
    # -S truncate rather than wraplong lines; type at runtime to toggle
    # -M verbose prompts
    # -R pass through raw control codes (e.g. ANSI color sequences)
    # -c better full screen repaints
    # -i case insensitive searches

    # TODO: only use 256 color when available
    # Old color scheme:
    # export LESS_TERMCAP_mb=$'\E[01;31m'
    # export LESS_TERMCAP_md=$'\E[01;31m'
    # export LESS_TERMCAP_me=$'\E[0m'
    # export LESS_TERMCAP_so=$'\E[01;44;30m'
    # export LESS_TERMCAP_se=$'\E[0m'
    # export LESS_TERMCAP_us=$'\E[01;32m'
    # export LESS_TERMCAP_ue=$'\E[0m'

    if [ "$BACKGROUND" = "light" ]; then
        # Light Less Colors
        export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
        export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
        export LESS_TERMCAP_me=$'\E[0m'           # end mode
        export LESS_TERMCAP_so=$'\E[01;44;37m'    # begin standout-mode - info box
        export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
        export LESS_TERMCAP_us=$'\E[04;38;5;27m'  # begin underline
        export LESS_TERMCAP_ue=$'\E[0m'           # end underline
    else
        # Dark Less Colors
        export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
        export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
        export LESS_TERMCAP_me=$'\E[0m'           # end mode
        # export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
        # export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
        export LESS_TERMCAP_so=$'\E[01;44;30m'    # begin standout-mode - info box
        export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
        export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline
        export LESS_TERMCAP_ue=$'\E[0m'           # end underline
    fi
fi
