#!/bin/sh
# shellcheck disable=SC3043
# before: bootstrap

find_ssh_sock()
{
  if [ -n "$SSH_AUTH_SOCK" ]; then
    return
  fi

  if systemctl --user whoami >/dev/null 2>&1; then
    local systemd_sock
    systemd_sock=$(systemctl --user show-environment | grep SSH_AUTH_SOCK | cut -d= -f2-)
    if [ -n "$systemd_sock" ]; then
      export SSH_AUTH_SOCK="$systemd_sock"
    fi
  fi

  if [ -z "$SSH_AUTH_SOCK" ]; then
    local gpg_sock
    gpg_sock=$(gpgconf --list-dirs agent-ssh-socket)
    if [ -n "$gpg_sock" ]; then
      export SSH_AUTH_SOCK=$gpg_sock
      echo 'Set SSH_AUTH_SOCK from gpg-agent'
    fi
  fi

  export_ssh_sock
}

export_ssh_sock() {
  if [ -z "$SSH_AUTH_SOCK" ]; then
    echo 'No SSH_AUTH_SOCK set to export'
    return
  fi

  if systemctl --user whoami >/dev/null 2>&1; then
    local systemd_sock
    systemd_sock=$(systemctl --user show-environment | grep SSH_AUTH_SOCK | cut -d= -f2-)
    if [ -z "$systemd_sock" ] || [ "$systemd_sock" != "$SSH_AUTH_SOCK" ]; then
      systemctl --user import-environment SSH_AUTH_SOCK
      echo 'Exported SSH_AUTH_SOCK into systemd'
    fi
  fi

  if type tmux >/dev/null; then
    tmux setenv -g SSH_AUTH_SOCK "$SSH_AUTH_SOCK"
    tmux setenv SSH_AUTH_SOCK "$SSH_AUTH_SOCK"
    echo 'Exported SSH_AUTH_SOCK into tmux'
  fi
}

find_ssh_sock

