#!/bin/bash

# Try to fix broken $TERM
if [ -n "$TERM" ] && which tput &>/dev/null; then
    while ! tput longname &>/dev/null; do
        [ -t 2 ] && echo -n "TERM=$TERM didn't work out..." >&2

        # if -256color, try lower color version
        if [[ "$TERM" = *-256color ]] && tput -T"${TERM%-256color}" longname &>/dev/null; then
            export TERM=${TERM%-256color}
            [ -t 2 ] && echo "using TERM=$TERM instead." >&2
            break
        fi

        # hmm, well if it's not linux, try that
        if [ "$TERM" != linux ] && tput -Tlinux longname &>/dev/null; then
            export TERM=linux
            [ -t 2 ] && echo "using TERM=$TERM instead." >&2
            break
        fi

        # finally, fallback on vt100
        export TERM=vt100
        [ -t 2 ] && echo "falling back to TERM=$TERM instead." >&2
    done
fi
