#!/bin/bash
# before: bootstrap
# after: path

# Privatize $TMPDIR
TMPDIR=${TMPDIR:-/tmp}
case $(stat --help 2>&1) in
*GNU*)
    if [ "$(stat -c %u "$TMPDIR")" -ne "$(id -u)" ]; then
        TMPDIR=$TMPDIR/$(id -un)
    fi
    ;;
*)
    if [ "$(stat -f %u "$TMPDIR")" -ne "$(id -u)" ]; then
        TMPDIR=$TMPDIR/$(id -un)
    fi
    ;;
esac
export TMPDIR
install -d -m 0700 "$TMPDIR"

ln -sf "$TMPDIR" "$HOME/tmp"
